package com.finter.india.utils

object Constants {

    const val FILE_TYPE_IMAGE_STR = "fileTypeImageStr"
    const val FILE_TYPE_VIDEO_STR = "fileTypeVideoStr"
    const val FILE_TYPE_Audio_STR = "fileTypeAudioStr"
    const val BASE_URL_MAP = "http://www.google.co.in/maps/dir/"


    const val NO_FIRST_TIME_LOGIN = "firstTimeLogin"
    const val ACTIVE_ACCOUNT = "activeAccount"
    const val BASIC_INFO_FILLED = "BasicInfoFilled"
    const val BANK_INFO_FILLED = "BankInfoFilled"
    const val TAX_INFO_FILLED = "taxInfoFilled"
    const val OTHER_INFO_FILLED = "otherInfoFilled"
    const val ALL_INFO_FILLED = "allInfoFilled"
    const val GST_APPLICABLE = "gstApplicable"
    const val E_WAYBILL_APPLICABLE = "eWayBillApplicable"
    const val RESTART_ACTIVITY = "restartActivity"
    const val REGISTRATION_TYPE_DATE = "registrationTypeDate"

    const val APP_FLOW = "appFlow"
    const val FROM_REGISTER = "1"
    const val FROM_NEW_FIRM_UPDATE = "3"
    const val FROM_NEW_FIRM = "4"
    const val FROM_UPDATE = "2"

    const val MOBILE = "mobile"
    const val BUSINESS_NAME = "businessName"
    const val BUSINESS_LOGO = "businessLogo"
    const val EMAIL = "email"
    const val FIRM_LIST = "firmList"
    const val YEAR_LIST = "yearList"
    const val FINANCIAL_YEAR_LIST = "financialYearList"
    const val CURRENT_YEAR_SERVER = "currentYearServer"
    const val CURRENT_YEAR_APP = "currentYearApp"
    const val CURRENT_TIME = "currentTime"
    const val FOR_THIRTY_SEC = "forThirtySec"
    const val FOR_THIRTY_MIN = "forThirtyMin"
    const val REMAINING_TIME = "remainingTime"
    const val REMAINING_TIME_ARRAY = "remainingTimeArray"
    const val START_THIRTY_MIN_TIMER = "startedThirtyMinTimer"

    const val UPDATE_CUSTOMER = "updateCustomer"
    const val ACTIVITY_CUSTOMER = "activityCustomer"
    const val FRAGMENT_CUSTOMER = "fragmentCustomer"
    const val Add_CUSTOMER = "addCustomer"
    const val FROM_CUSTOMER = "fromCustomer"
    const val LIST_CUSTOMER = "listCustomer"
    const val LIST_CUSTOMER_ATTACHMENT = "listCustomerAttachment"
    const val LOGIN = "login"
    const val FORGOT_PASSWORD = "forgotPassword"
    const val ACTIVITY_NAME = "activityName"
    const val ACTIVITY_PAYMENT_NAME = "activityPaymentName"
    const val SALES_PERSON_ADD = "salesPersonAdd"
    const val SALES_PERSON_UPDATE = "salesPersonUpdate"
    const val VERIFY_OTP = "verify_otp"
    const val REGISTER = "register"
    const val USER_ID = "userId"
    const val USER_NAME = "userName"
    const val ROLE = "role"
    const val STATE_LIST = "stateList"
    const val UNIT_LIST = "unitList"
    const val COUNTRY_LIST = "countryList"
    const val All_ID = "Customer_Id"
    const val PENDING = "Pending"
    const val CHALLAN_ID = "challanId"

    const val INVOICE_ACTIVITY = "InvoiceActivity"
    const val INVOICE_ADD_PRODUCT = "invoiceAddProduct"
    const val INVOICE_UPDATE_PRODUCT = "invoiceUpdateProduct"
    const val UPDATE_CUSTOMER_BOOLEAN = "updateCustomerBoolean"
    const val PRODUCT_LIST = "productList"
    const val TEMP_PRODUCT_LIST = "tempProductList"
    const val INVOICE_DATA = "invoiceData"
    const val PRODUCT_ID_ARRAY = "productIdArray"
    const val PRODUCT_ID_ARRAY_JSON = "productIdArrayJson"
    const val INVOICE_PRODUCT_IN_NEGATIVE = "invoiceProductInNegative"
    const val AGAINST_INVOICE_RECEIVE = "againstInvoiceReceive"
    const val OTHER_AGAINST_INVOICE_RECEIVE = "againstInvoiceReceive"
    const val AGAINST_INVOICE_PAYMENT = "OtherAgainstInvoicePayment"
    const val OTHER_AGAINST_INVOICE_PAYMENT = "OtherAgainstInvoicePayment"
    const val CONTRA_ENTRY = "contraEntry"
    const val CONTRA_ENTRY_LIST = "contraEntryList"
    const val EXPENSE_ENTRY = "expenseEntry"
    const val EXPENSE_ENTRY_LIST = "expenseEntryList"
    const val PAYMENT_MADE = "paymentMade"
    const val PAYMENT_MADE_LIST = "paymentMadeList"
    const val PAYMENT_RECEIVE = "paymentReceive"
    const val PAYMENT_RECEIVE_LIST = "paymentReceiveList"
    const val NEGATIVE_STOCK = "negativeStock"
    const val INVOICE = "invoice"
    const val RECEIPT_PAYMENT = "receiptPayment"
    const val REPORT = "report"
    const val RECEIPT = "receipt"
    const val PAYMENT = "payment"
    const val FCM_TOKEN = "fcmToken"
    const val DEVICE_ID = "deviceId"
    var MAINTENANCE_MESSAGE_HEADER = ""
    var MAINTENANCE_MESSAGE_FOOTER = ""
    var MAINTENANCE_MESSAGE_IMAGE = ""

    const val NOTIFICATION_MESSAGE_HEADER = "notificationMessageHeader"
    const val NOTIFICATION_MESSAGE_FOOTER = "notificationMessageFooter"
    const val NOTIFICATION_MESSAGE_IMAGE = "notificationMessageImage"

    const val PAYMENT_AGAINST_INVOICE_LIST = "paymentAgainstInvoiceList"
    const val PAYMENT_AGAINST_INVOICE = "paymentAgainstInvoice"
    const val PAYMENT_ADVANCE_INVOICE_LIST = "paymentAdvanceInvoiceList"
    const val PAYMENT_ADVANCE_INVOICE = "paymentAdvanceInvoice"
    const val PAYMENT_OTHER_LIST = "paymentOtherList"
    const val PAYMENT_OTHER_INVOICE = "paymentOther"

    const val ACCOUNT_TOKEN = "accountToken"
    const val FIRM_TOKEN = "firmToken"
    const val BASIC_INFO_BOOLEAN = "BasicInfoBoolean"
    const val BANK_INFO_BOOLEAN = "BankInfoBoolean"
    const val TAX_INFO_BOOLEAN = "taxInfoBoolean"
    const val OTHER_INFO_BOOLEAN = "otherInfoBoolean"

    const val BASIC_INFO_DATA = "BasicInfoData"
    const val COMPANY_INFO_DATA = "CompanyInfoData"
    const val BANK_INFO_DATA = "BankInfoData"
    const val TAX_INFO_DATA = "taxInfoData"
    const val OTHER_INFO_DATA = "otherInfoData"
    const val CALCULATION_DATA = "calculationData"


    const val CUSTOMER_LIST = "customerList"
    const val CUSTOMER_SEARCH_LIST = "customerSearchList"

    const val SALES_PERSON_LIST = "customerList"
    const val SALES_PERSON_SEARCH_LIST = "customerSearchList"

    const val SUPPLIER_LIST = "supplierList"
    const val SUPPLIER_SEARCH_LIST = "supplierSearchList"

    const val BASE_URL = "http://18.221.223.84/api/v1/"

    //    const val BASE_URL = "http://developmentlink.in/finter_development/api/v2/"
    const val BASE_URL_IFSC = "https://api.techm.co.in/api/v1/ifsc/"

    const val CLICK_TIME = 250
    const val REQUEST_CODE_WRITE_STORAGE_PERMISION = 105
    const val MEDIA_LOCATION_PERMISSION_REQUEST_CODE = 3
    const val OPEN_FILE_REQUEST_CODE = 1
    const val FILE_PROVIDER_AUTHORITY = "com.finter.india.provider"
    const val CAMERA = 6
    const val CHOOSE_FILE = 4

    // Entry Type
    const val ESTIMATE_ORDER_FLAG = "estimateOrderFlag"
    const val PURCHASE_ORDER_FLAG = "2"
    const val SALES_ORDER_FLAG = "3"
    const val ESTIMATE_FLAG = "4"
    const val PURCHASE_INVOICE_FLAG = "5"
    const val SALES_INVOICE_FLAG = "6"
    const val PROFORMA_INVOICE_FLAG = "7"
    const val DELIVERY_CHALLAN_FLAG = "8"
    const val CREDIT_NOTE_FLAG = "9"
    const val DEBIT_NOTE_FLAG = "10"
    const val BANK_CASH_RECEIPT = "11"
    const val BANK_CASH_PAYMENT = "13"
    const val STOCK_JOURNAL = "17"
    const val GST_EXPENSE = "18"
    const val GST_EXPENSE_COUNT = "18"
    const val JOURNAL_ENTRY = "16"

    const val IGST_FLAG = "2"
    const val TAX_FREE_FLAG = "3"
    const val UTGST_FLAG = "4"
    const val EXPORT_FLAG = "5"
    const val SGST_FLAG = "1"

    const val PRODUCT_IN_OUT = "productInOut"
    const val PRODUCT_IN = "1"
    const val PRODUCT_OUT = "2"

    const val PRODUCT_GST_INCLUDE = "1"
    const val PRODUCT_GST_EXCLUDE = "2"

    const val ACCOUNT_MASTER_CUSTOMER = "1"
    const val ACCOUNT_MASTER_SUPPLIER = "2"
    const val ACCOUNT_MASTER_LEDGER = "3"

    const val ALL_INVOICE_LIST = "allInvoiceList"
    const val SALES_REPORT = "1"
    const val SALES_REGISTER = "2"
    const val CREDIT_NOTE_REGISTER = "3"
    const val DEBIT_NOTE_REGISTER = "4"
    const val PURCHASE_REPORT = "5"
    const val PURCHASE_REGISTER = "6"
    const val OUTSTANDING_RECEIVABLE = "7"
    const val OUTSTANDING_PAYABLE = "8"
    const val ACCOUNT_LEDGER = "9"
    const val ACCOUNT_LEDGER_DETAILS = "10"
    const val CASH_BOOK = "11"
    const val CASH_BOOK_DETAILS = "12"
    const val BANK_BOOK = "13"
    const val BANK_BOOK_DETAILS = "14"
    const val PRODUCT = "15"
    const val PRODUCT_DETAILS = "16"

}